operator:
  enable: true
  imagePullPolicy: Always
  image: ghcr.io/digizuite/postgres-topology-operator:master
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
  nodeSelector: {}
