apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-topology-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: postgres-topology-operator
    app.kubernetes.io/name: postgres-topology-operator
    app.kubernetes.io/part-of: postgres
  name: postgres-topology-operator-role
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - postgres.digizuite.com
    resources:
      - postgresschemas
      - postgresadminconnections
      - postgresroles
      - pgbouncers
      - pgbouncerusers
      - pgbouncerdatabases
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - postgres.digizuite.com
    resources:
      - postgresschemas/finalizers
      - postgresadminconnections/finalizers
      - postgresroles/finalizers
      - pgbouncers/finalizers
      - pgbouncerusers/finalizers
      - pgbouncerdatabases/finalizers
    verbs:
      - update
      - patch
  - apiGroups:
      - postgres.digizuite.com
    resources:
      - postgresschemas/status
      - postgresadminconnections/status
      - postgresroles/status
      - pgbouncers/status
      - pgbouncerusers/status
      - pgbouncerdatabases/status
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: postgres-topology-operator
    app.kubernetes.io/name: postgres-topology-operator
    app.kubernetes.io/part-of: postgres
  name: postgres-topology-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-topology-operator-role
subjects:
  - kind: ServiceAccount
    name: postgres-topology-operator
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-topology-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: postgres-topology-operator
    app.kubernetes.io/name: postgres-topology-operator
    app.kubernetes.io/part-of: postgres
spec:
  replicas: {{ .Values.operator.enable | ternary 1 0 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-topology-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres-topology-operator
        app.kubernetes.io/name: postgres-topology-operator
        app.kubernetes.io/part-of: postgres
    spec:
      serviceAccountName: postgres-topology-operator
      imagePullSecrets:
        - name: {{ .Values.operator.imagePullSecret }}
      containers:
        - name: operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          env:
            - name: RUST_LOG
              value: "info"
          resources:
            limits:
              cpu: {{ .Values.operator.resources.limits.cpu }}
              memory: {{ .Values.operator.resources.limits.memory }}
            requests:
              cpu: {{ .Values.operator.resources.requests.cpu }}
              memory: {{ .Values.operator.resources.requests.memory }}
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .Values.operator.nodeSelector | nindent 8 }}
